User.create!(name: "カメラのやました", email: "camera@gmail.com", password: "123456",  image: File.open('./app/assets/images/camera.jpg'), introduction: "大阪 兵庫中心で撮影してます。主に動物メインに風景や人物も撮ります！カメラ友募集中です！主にInstagramで活動しています。リンク先にInstagramのアカウントを貼っておきますので覗いてみてください！使用カメラ → Canon Kiss X7",link: "https://www.instagram.com/", skill: "カメラ、画像編集（Adobe社の画像加工ソフト「Photoshop」使用）" ,career: "〇〇高校卒 → 〇〇大学", award: "「第４０回日本絶景大賞 内閣総理大臣賞」受賞、第三回フォトジェニックコンテスト 金賞", certificate: "1級写真技能士、クリエイター能力認定試験")
User.create!(name: "スラお", email: "suraimu@gmail.com", password: "123456", image: File.open('./app/assets/images/suraimu.jpg'), introduction: "凡人が営業を学んだ結果…60ヵ月連続売上No1 → 若手役員、商業出版の依頼が発生、最短で結果を出せたのは泥臭く、365日休まず一人ブラック企業を続けただけ、後天的に身につけた営業力を使って影響力を拡散中！",link: "https://coconala.com/", skill: "ライティング、営業、コンサル", career: "〇〇大卒 → 〇〇社５年勤務", award: "営業：〇〇エリア五年連続一位、2020年△△ビジネス書大賞ノミネート", certificate: "マイクロソフトオフィススペシャリスト（MOS）、TOEIC900点")
User.create!(name: "クッキングママ", email: "cooking@gmail.com", password: "123456", image: File.open('./app/assets/images/cooking.jpg'), introduction: "都内某レストランシェフ/料理研究家。分子ガストロノミーの知識を使った魔法のような料理を演出します。YouTubeを開設したのでそちらも合わせて御覧ください。", link: "https://www.youtube.com/", skill: "主に洋食、海外仕込みの分子ガストロノミー", career: "レストリア〇〇五年 → 渡仏 → 三ツ星店○✗で五年間スーシェフを経験。", award: "第43回レシピ本大賞受賞", certificate: "野菜ソムリエ、専門調理師免許、フードアナリスト")
User.create!(name: "レゴ太郎", email: "lego@gmail.com", password: "123456", image: File.open('./app/assets/images/lego.jpg'), introduction: "レゴ®認定プロビルダー（LEGO Certified Professional）世界で21人しかいないプロのレゴ職人／〇〇展で作品展示中。", link: "", skill: "レゴ", career: "〇〇大学卒 → プロのレゴビルダーとして生計をたてる", award: "第3回レゴブロック作品コンテスト 最優秀賞", certificate: "レゴ®シリアスプレイ®研修済み・認定ファシリテーター")
User.create!(name: "100均のカレンダー", email: "calendar@gmail.com", password: "123456", image: File.open('./app/assets/images/calendar.jpg'), introduction: "【最強無敵の新進気鋭マーケター】わずか三ヶ月でYouTube登録者数5万。Twitterのフォロワー数10万人超え。その他の詳細はリンク先をクリック↓↓", link: "https://twitter.com/home", skill: "マーケティング、WEB製作、SNS運用、SEO対策", career: "鹿児島出身▶︎高校首席卒▶︎○大▶︎○大院▶︎△✗社▶︎Web系エンジニア▶︎独立", award: "", certificate: "")
User.create!(name: "プログラミングバブ", email: "babu@gmail.com", password: "123456", image: File.open('./app/assets/images/babu.jpg'), introduction: "０歳ですがプラグラミングができます！", link: "https://railsguides.jp/getting_started.html", skill: "Ruby on rails/javascript/Python", career: "五ヶ月前に生誕", award: "プログラミングコンテスト小学生の部 金賞", certificate: "ソリューションアーキテクト")
User.create!(name: "officialちょびヒゲ公爵", email: "hige@gmail.com", password: "123456", image: File.open('./app/assets/images/hige.png'), introduction: "officialなちょび髭公爵（公式）です。",link: "https://www.youtube.com/", skill: "歌唱力、作詞作曲", career: "大手レコード会社〇〇所属。", award: "第46回日本レコード大賞受賞", certificate: "")
User.create!(name: "大天聖☆ミカエル", email: "mahoutukai@gmail.com", password: "123456", image: File.open('./app/assets/images/mahoutukai.jpg'), introduction:"新進気鋭の駆け出しラノベ作家です。△△レーベルから〇〇１巻〜８巻好評発売中！来年の春にアニメ化決定！",link: "https://kakuyomu.jp/", skill: "物語構成、演出、世界観の設定、執筆全般", career: "〇〇大学卒→普段はしがないサラリーマンをしています。", award: "「第２８回電撃大賞 大賞」/「第７８回MF文庫J新人賞　金賞」", certificate: "ワープロ検定一級、検索技術者検定１級")
User.create!(name: "ベジタリアン星人", email: "gokuu@gmail.com", password: "123456", image: File.open('./app/assets/images/gokuu.png'), introduction: "イラストレーターです。代表作：「〇〇の✗✗！」「84940分の位置」「ようこそ○✗△へ」など。",link: "https://www.fanbox.cc/", skill: "", career: "○△専門学校卒  → デザイン会社〇〇で五年勤務 → フリーランス", award: "○□イラスト大賞 銀賞", certificate: "")
User.create!(name:"ピカペコ", email: "pikachu@gmail.com", password: "123456", image: File.open('./app/assets/images/pikachu.jpg'), introduction: "アラフォー翻訳家（英日）／自分が苦労した体験を元に楽しく英語を身につける方法をブログ↓↓で発信中。海外で戦いたいマン。一緒にでかいプロジェクトに挑戦しませんか？", link: "https://official.ameba.jp/", skill:"", career: "アメリカ留学→英会話学校講師→外資の社畜→独立", award: "", certificate: "TOEIC(LR)満点/英検1級/言語学修士")
User.create!(name:"クレイジーピエロ", email: "piero@gmail.com", password: "123456", image: File.open('./app/assets/images/piero.jpg'), introduction: "表の顔は俳優。裏の顔はYouTuber兼Tik Toker。登録者数143万人超え！海外への挑戦を視野に活動中。", link: "https://www.youtube.com/", skill: "演技、動画製作", career: "", award: "第48回日本アカデミー賞 助演男優賞受賞", certificate: "ひよこ鑑定士")

Post.create!(user_id: 2,title: "ブログをはじめました",product: "ブログを書いてみました。日々の学びや気づきを発信できたらいいなと思います。",link: "",skill: "ライティング")
Post.create!(user_id: 2, title: "SNSの運用", product: "一年でフォロワー数が十万人も伸びました。僕のTwitterをフォローすれば毎日、有益で新鮮な情報にキャッチアップできます。僕のTwitterのアカウントをリンク先に貼っておきますので興味がある方はフォローをよろしくお願いします！", link: "https://twitter.com/home", skill: "SEO対策、SNS運用",image: File.open('./app/assets/images/Twitter.jpg'))
Post.create!(user_id: 3,title: "モンブラン", product: "モンブランを製作しました。栗はイタリアから取り寄せたこだわりの一品です。",skill: "お菓子作り",image: File.open('./app/assets/images/image0-2.jpg'))
Post.create!(user_id: 5,title: "せどりをした結果.....", product: "せどりだけで純利益１億円を突破しました。培ってきた知識を公開し、興味のある方を対象としたコンサルを個別でする予定です。",skill: "仕入れ、マーケティング")
Post.create!(user_id: 6,title: "アプリをつくってみました",product: "GoogleAPIを用いて簡単な天気予報アプリを作ってみました。リンクを貼っておきます。",link: "",skill: "使用言語：Ruby/javascript")
Post.create!(user_id: 7, title: "新曲の楽譜",product: "作曲した新曲の楽譜になります",link: "",skill: "DAW、絶対音感",image: File.open('./app/assets/images/gakuhu.png'))
Post.create!(user_id: 7, title: "アレンジで演奏してみました",product: "大人気ロックバンドのofficial◯男dismの代表曲である『Pretender』をアレンジして弾いてみました！リンク先で実際に視聴できます。",link: "https://www.youtube.com/watch?v=qU30ENz5au8",skill: "ギター、作曲")
Post.create!(user_id: 8,title: "小説を執筆してみました",product: "新作を執筆しました。タイトルは『転生したら竜になっていて玉を７つ集めた者に願いを叶えろだって？』です。最近流行りの転生もので、竜になった主人公と７つの玉を集めた冒険者が「主人公を下僕にする」という願いをしたことによって奴隷のような扱いをうけることから始まる快活活劇です！リンク先で実際に読めます",link: "https://ncode.syosetu.com/n0423gu/",skill: "文章力、構成、演出力、キャラクター制作")
Post.create!(user_id: 9,title: "女の子の絵を書いてみました",product: "可愛い女の子のイラストです！落書きクオリティですが感想をお願いします。",skill: "イラスト、デザイン",image: File.open('./app/assets/images/girl.png'))
Post.create!(user_id: 10,title: "海外の記事を翻訳してみました",product: "海外の記事を翻訳しました。以下、日本語訳を貼っておきます。リンク先は参考にした記事です。ロシアはCOVID-19ワクチンを製造しています。ワクチンは、病気があなたを病気にするのを防ぐことができる薬です。ロシアは、公式のCOVID-19ワクチンを製造する世界で最初の国です。
  ロシアの大統領は、ワクチンは安全だと言っています。彼は医者がワクチンを使うことができると言います。彼の娘はワクチンを接種します。彼女は気分がいい。彼女は深刻な健康上の問題はありません。ロシア当局は、ワクチンは2年間人を守ることができると言います。
  しかし、他の国の科学者たちは心配しています。彼らはワクチンが良いとは信じていません。彼らは、テストが十分に長くは続かないと言います。すべてのワクチンには長いテストがあります。多くの人がテストに参加する必要があります。しかし、ロシアはワクチンを非常に迅速に製造しています。
  難しい言葉：作る（何かを起こすため）、公式（官公庁が何かを言うとき）、保護する（誰かを安全に保つため）。レベル3のセクションで元のビデオを見ることができます。",link: "https://www.newsinlevels.com/products/first-covid-19-vaccine-level-1/",skill: "英語、翻訳")
Post.create!(user_id: 11, title: "動画編集してみました",product: "テロップ、効果音を加えて動画編集をしてみました。リンクを下に貼っておきます。リンクはYouTubeへ飛びます。",link: "https://www.youtube.com/",skill: "動画編集")
Post.create!(user_id: 11,title: "演技をしてみた", product: "犬の演技をしてみましたワン。YouTubeのリンクを貼っておきますワン！ワンワン！",link: "https://www.youtube.com/",skill: "演技力")

Board.create!(user_id:11 , title: "動画』×『翻訳』", essential: "三年ほど動画というコンテンツを武器に戦ってきましたが、次第に海外に挑戦したいという欲求が芽生え始めるようになってきました。しかし、僕はまだ英語を習い始めたばかりで、自由自在に言葉を使いこなせません。コンテンツの性質上、それでは海外向けの発信ができないという考えに至りました。そこで僕の『動画製作』のスキルとどなた様かの『翻訳』のスキルを組み合わせて無敵のコンテンツを作れば最強じゃね？と思いました。我こそはと思う方がいれば、ぜひご相談くださると嬉しいです。", requirement: "英語の翻訳が可能な人。独特な言い回しをユニークな表現へと変換できる柔軟な発想を持っている人", address: "DMまで連絡ください")
Board.create!(user_id: 3, title: "料理の『写真集』がメインのレシピ本を作りたい", essential: "これまでレシピ本は数多く出版されてきましたが、『料理』そのものを主役に据えたレシピ本はまだ出版されていないなと思い、今回の企画を立案しました。月並みな表現ではありますが、料理は芸術です。そんな芸術品の一瞬を切り取り、最高の瞬間をいつまでも楽しんでいただけるような写真集を作りたいと思っております。", requirement: "写真の腕に自信がある方。自身が撮った作品のデータを5つほど添付して以下のメールアドレスまでお送りください。", address: "〇〇@gmail.comまで連絡ください")
Board.create!(user_id: 6, title: "自作ゲームの世界観にあったイラストを書いてほしい", essential: "一年かけて自作のゲームを一人で開発しました。今は懐かしきドット画風のRPGなのですが、いかんせん画がフリー素材なため、どうも安っぽさが出てしまっています。もしよろしければ、お力をかしていただけると嬉しいです。", requirement: "イラストに自信がある人。", address: "DMまで連絡ください")
Board.create!(user_id: 7, title: "楽曲の世界観にマッチしたPVの製作", essential: "新曲を作成したのですが、再生数が伸びません。そこでメンバーで話し合った結果、PVをつけようと決まりました。どなたか曲の世界観にあったPVを製作してくださる方はいませんか？", requirement: "撮影から編集までを一任できる方", address: "DMまで連絡ください")
Board.create!(user_id: 8, title: "オリジナルのアニメを作りたい！", essential: "私が書いている小説を原作にしたアニメーションを作成しょうと考えております。そこでイラストが得意な方にご参加していただきたいと思っております。", requirement: "オリジナルアニメーションに興味のある方", address: "DMまで連絡ください")
Board.create!(user_id: 1, title: "展覧会をやります！", essential: "六本木で展覧会を開催予定です！テーマである『共存』という言葉をもとに、他分野のクリエイターに数多く参加していただきたいと思っております。一緒に展覧会を成功させていただけると嬉しいです！興味がある方はDMまでご連絡をお願いします。", requirement: "『共存』というテーマに沿った作品を出品できるクリエイター", address: "DMまで連絡ください")
Board.create!(user_id: 8, title: "『ガストロノミー』で作中のご飯を表現しませんか？", essential: "作中に出てくる料理を現実で再現してほしいです。コンセプトが魔法を使った料理であるため、そこに科学で対抗したいなと思いました。", requirement: "ガストロノミーの知識がある料理経験者の方", address: "DMまで連絡ください")
Board.create!(user_id: 4, title: "クリエイターのシェアハウスを建設中！", essential: "六人の男女が一つ屋根の下で暮らせるようなシェアハウスを建設中です。入居条件は『何かしらのクリエイター』であること。その模様をYouTubeに定期的に配信しようと考えております。恋愛に夢に頑張りたい方はぜひご応募していただけると嬉しいです。", requirement: "25歳以下の男女。何かしらクリエイティブな職に就かれている方、もしくは目指されている方。YouTubeに顔出し出演がオッケーな方。", address: "DMまで連絡ください")
Board.create!(user_id: 11, title: "アカウントの運用（中の人）をお願いしたいです！", essential: "生まれたての子供の物覚えがよく、芸人さんのネタを教えるとすぐに真似します。その様子をYouTubeにUPしたところたくさんの反響をいただきました。そこでこの人気にあやかってSNSアカウントの開設と運用したいと考えております。", requirement: "SNSの運用に強い方", address: "DMまで連絡ください")
Board.create!(user_id: 8, title: "オリジナルアニメのOP主題歌を歌ってほしい", essential: "私が書いている小説を原作にしたアニメーションを作成しょうと考えております。そこで主題歌を歌ってくれる人のオーディションを開催します。", requirement: "歌唱力に自信のある人", address: "DMまで連絡ください")
Board.create!(user_id: 4, title: "理想の秘密基地を一緒につくりませんか？", essential: "レゴで理想の秘密基地を作成してみました。そこでこれを実際にアイデアを出し合いながら実際に建設してみたいと考えております。", requirement: "建築の知識がある方", address: "DMまで連絡ください")

Tag.create!(tag_name: "ライティング")
Tag.create!(tag_name: "料理")
Tag.create!(tag_name: "プラグラミング")
Tag.create!(tag_name: "写真")
Tag.create!(tag_name: "せどり")
Tag.create!(tag_name: "秘密基地")
Tag.create!(tag_name: "音楽")
Tag.create!(tag_name: "イラスト")
Tag.create!(tag_name: "小説")
Tag.create!(tag_name: "SNS運用")
Tag.create!(tag_name: "ゲーム")
Tag.create!(tag_name: "歌ってみた")
Tag.create!(tag_name: "アニメ")
Tag.create!(tag_name: "漫画")
Tag.create!(tag_name: "翻訳")
Tag.create!(tag_name: "英語")
Tag.create!(tag_name: "動画製作")
Tag.create!(tag_name: "モノマネ")
Tag.create!(tag_name: "ナレーション")
Tag.create!(tag_name: "動物")
Tag.create!(tag_name: "世界観")
Tag.create!(tag_name: "ファンタジー")
Tag.create!(tag_name: "YouTube")
Tag.create!(tag_name: "Twitter")
Tag.create!(tag_name: "Instagram")
Tag.create!(tag_name: "世界規模")
Tag.create!(tag_name: "のど飴")
Tag.create!(tag_name: "人形")
Tag.create!(tag_name: "感動")
Tag.create!(tag_name: "異世界転生")
Tag.create!(tag_name: "六本木")
Tag.create!(tag_name: "コミケ")
Tag.create!(tag_name: "夏コミ")
Tag.create!(tag_name: "東京ビックサイト")
Tag.create!(tag_name: "アテレコ")
Tag.create!(tag_name: "エモい")
Tag.create!(tag_name: "学生")
Tag.create!(tag_name: "被写体")
Tag.create!(tag_name: "モデル")
Tag.create!(tag_name: "レゴ")
Tag.create!(tag_name: "建築")
Tag.create!(tag_name: "ガストロノミー")

Tagmap.create!(tag_id: 1,post_id: 1)
Tagmap.create!(tag_id: 9,post_id: 2)
Tagmap.create!(tag_id: 2,post_id: 3)
Tagmap.create!(tag_id: 5,post_id: 4)
Tagmap.create!(tag_id: 3,post_id: 5)
Tagmap.create!(tag_id: 7,post_id: 6)
Tagmap.create!(tag_id: 7,post_id: 7)
Tagmap.create!(tag_id: 9,post_id: 8)
Tagmap.create!(tag_id: 8,post_id: 9)
Tagmap.create!(tag_id: 15,post_id: 10)
Tagmap.create!(tag_id: 17,post_id: 11)
Tagmap.create!(tag_id: 18,post_id: 12)